// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUqoE_lwDCCz8A-5twZ-PxEdo9qEEehqA',
    appId: '1:250135126119:web:eae0ff70504c5cc59af4c2',
    messagingSenderId: '250135126119',
    projectId: 'nexq-fcebc',
    authDomain: 'nexq-fcebc.firebaseapp.com',
    storageBucket: 'nexq-fcebc.firebasestorage.app',
    measurementId: 'G-TMM82CFTM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlOK6s2-MGbtFH-Fh9QUEcBlOj-bzVe9c',
    appId: '1:250135126119:android:883455d8c247fb079af4c2',
    messagingSenderId: '250135126119',
    projectId: 'nexq-fcebc',
    storageBucket: 'nexq-fcebc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiKkQLMp89X3rwnX7MPgHMF_GYzcWN6xU',
    appId: '1:250135126119:ios:331714daba5a7bdc9af4c2',
    messagingSenderId: '250135126119',
    projectId: 'nexq-fcebc',
    storageBucket: 'nexq-fcebc.firebasestorage.app',
    androidClientId: '250135126119-gctr2ikefdrv16ov2t70dcu2g3sk250d.apps.googleusercontent.com',
    iosClientId: '250135126119-9m8f4tgjrq0mca35vjngil62jjc8r0j6.apps.googleusercontent.com',
    iosBundleId: 'com.nexq.nexq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiKkQLMp89X3rwnX7MPgHMF_GYzcWN6xU',
    appId: '1:250135126119:ios:331714daba5a7bdc9af4c2',
    messagingSenderId: '250135126119',
    projectId: 'nexq-fcebc',
    storageBucket: 'nexq-fcebc.firebasestorage.app',
    androidClientId: '250135126119-gctr2ikefdrv16ov2t70dcu2g3sk250d.apps.googleusercontent.com',
    iosClientId: '250135126119-9m8f4tgjrq0mca35vjngil62jjc8r0j6.apps.googleusercontent.com',
    iosBundleId: 'com.nexq.nexq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUqoE_lwDCCz8A-5twZ-PxEdo9qEEehqA',
    appId: '1:250135126119:web:df04d4dff64c872b9af4c2',
    messagingSenderId: '250135126119',
    projectId: 'nexq-fcebc',
    authDomain: 'nexq-fcebc.firebaseapp.com',
    storageBucket: 'nexq-fcebc.firebasestorage.app',
    measurementId: 'G-PJGTNMY11W',
  );

}